version: 2
registries:
  python-index-pypi-org:
    type: python-index
    url: https://pypi.org/
    replaces-base: true
    username: "${{secrets.PYTHON_INDEX_PYPI_ORG_USERNAME}}"
    password: "${{secrets.PYTHON_INDEX_PYPI_ORG_PASSWORD}}"

updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "19:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: flake8
    versions:
    - 3.8.3
  registries:
  - python-index-pypi-org
- package-ecosystem: docker
  directory: "/.docker"
  schedule:
    interval: daily
    time: "19:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: amazeeio/python
    versions:
    - 2.7.pre.ckan.pre.20.12.0
    - 2.7.pre.ckan.pre.21.2.0
    - 2.7.pre.ckan.pre.21.2.1
  - dependency-name: amazeeio/solr
    versions:
    - 6.6.pre.ckan.pre.20.12.0
    - 6.6.pre.ckan.pre.21.2.0
    - 6.6.pre.ckan.pre.21.2.1
