---
- name: Cloudformation Playbook
  hosts: local
  connection: local

  pre_tasks:
    - name: Set basic facts
      import_tasks: basic_facts.yml

    - name: Look up baseline machine image
      set_fact:
        base_ami: "{{ environment_ssm_vars[ssm_env_prefix + '/common/BaselineAmiId'] }}"

    - include_vars: vars/AMI-template-instances.var.yml

  roles:
    - ansible_cloudformation
