---
- name: Cloudformation Playbook
  hosts: local
  connection: local
  vars_files:
    - vars/cloudfront-certificates.var.yml
  pre_tasks:
    - name: Get CKAN legacy theme source for environment, if any
      set_fact:
        CKANThemeSource={{ item.CKANThemeSource }}
      when: item.Environment == Environment and item.profile == lowercase_name
      with_items: "{{ certificate_arns }}"

    - include_vars: vars/CKAN-extensions.yml
  roles:
    - ansible_cloudformation
