---
- name: Cloudformation Playbook
  hosts: local
  connection: local
  vars_files:
    - vars/cloudfront-certificates.var.yml
  pre_tasks:
    - name: Get public domain for environment
      set_fact:
        Domain={{ item.Domain }}
      when: item.Environment == Environment and item.profile == lowercase_name
      with_items: "{{ certificate_arns }}"

    - include_vars: vars/CKAN-Stack.yml
  roles:
    - ansible_cloudformation
