---
- name: Cloudformation Playbook
  hosts: local
  connection: local
  pre_tasks:
    - name: Set basic facts
      import_tasks: basic_facts.yml

    - include_vars:
        file: vars/cloudfront-logging-bucket.var.yml
  roles:
    - ansible_cloudformation
