---
- name: Cloudformation Playbook
  hosts: local
  connection: local
  pre_tasks:
    - name: get basic_facts
      set_fact:
        basic_fact={{ item }}
      when: item.Environment == Environment
      with_items: "{{ basic_facts }}"

    - name: set facts to environment from basic_fact
      set_fact: "{{ item.key }}={{ item.value }}"
      with_dict: "{{ basic_fact }}"
      when: basic_fact is defined

  roles:
    - ansible_cloudformation
