---
- name: Set up CKAN autoscaling groups
  hosts: local
  connection: local
  pre_tasks:
    - name: Set basic facts
      import_tasks: basic_facts.yml

    - name: Look up baseline machine image
      set_fact: "base_ami={{ lookup('aws_ssm', '/config/CKAN/' + Environment + '/common/BaselineAmiId') }}"

    - include_vars: vars/instances-{{ service_name }}.var.yml
  roles:
    - ansible_cloudformation
