---
- name: OpsWorks deployment
  hosts: local
  connection: local
  vars_files:
    - vars/CKAN-Stack.yml
  pre_tasks:

    - name: Identify CloudFormation stack
      set_fact:
        Stack_Name: "{{ item.name }}"
      when: item.template_parameters.Environment == Environment
      with_items: "{{ cloudformation_stacks }}"

    - name: Get CloudFormation stack ID
      cloudformation_facts:
        region: "{{ region }}"
        stack_name: "{{ Stack_Name }}"
        stack_resources: true
      register: cf_facts
    - set_fact:
        stack_id: "{{ cf_facts.ansible_facts.cloudformation[Stack_Name].stack_outputs.StackID }}"

  roles:
    - ansible_opsworks
