---
- name: Cloudformation Playbook
  hosts: local
  connection: local
  gather_facts: yes
  vars_files:
    - vars/security_groups.yml
  pre_tasks:

    - name: Obtain list of AWS IPs
      uri:
        url: https://ip-ranges.amazonaws.com/ip-ranges.json
        method: GET
        force: yes
      register: aws_ips

    - name: Convert list of AWS Ips to json object
      set_fact:
        aws_ipv4_json: "{{ aws_ips.json.prefixes }}"
        aws_ipv6_json: "{{ aws_ips.json.ipv6_prefixes }} "

    - name: Compile Jinja2 Security Group template
      template:
        src: security_groups.cfn.yml.j2
        dest: templates/security_groups.cfn.yml

  roles:
    - ansible_cloudformation
