#!/usr/bin/env sh
##
# Add a CKAN account if it doesn't already exist.
#
set -e
set -x

echo "Adding user '$2' ($1) with email address [$3]"
ckan_cli user show "$1" | grep "$1" || ckan_cli user add "$1"\
    fullname="$2"\
    email="$3"\
    password="${4:-Password123!}"
