---
cloudformation_stacks:
  - name: CKAN-PROD-RDS
    state: "{{ state | default('present')}}"
    region: ap-southeast-2
    disable_rollback: true
    template: "templates/database.cfn.yml"
    template_parameters:
      DBAllocatedStorage: "100"
      DBClass: db.m5.large
      DBEngine: postgres
      DBEngineVersion: 10.6
      DBName: ckan
      StorageEncrypted: "True"
      DBPassword: "{{ lookup('aws_ssm', '/config/CKAN/PROD/db/master_password', region='ap-southeast-2') }}"
      DBUsername: "{{ lookup('aws_ssm', '/config/CKAN/PROD/db/master_user', region='ap-southeast-2') }}"
      DBPrivileges: "ALL"
      Environment: PROD
      Platform: CKAN
      PubliclyAccessible: "false"
      MultiAZ: "true"
      Subnets: PRODCKANDBSubnet
      VPC: CKANVpc-PROD
      StackTLD: ckan.services.qld.gov.au
    tags:
      Environment: PROD
      Service: CKAN
      itoc_monitored: "false"
      Division: "Qld Online"
      Owner: "Development and Delivery"
      Version: "1.0"
      PowerManaged: "No"

  - name: CKAN-STAGING-RDS
    state: "{{ state | default('present')}}"
    region: ap-southeast-2
    disable_rollback: true
    template: "templates/database.cfn.yml"
    template_parameters:
      DBAllocatedStorage: '50'
      DBClass: db.t3.large
      DBEngine: postgres
      DBEngineVersion: 10.6
      DBName: ckan
      StorageEncrypted: "True"
      DBPassword: "{{ lookup('aws_ssm', '/config/CKAN/STAGING/db/master_password', region='ap-southeast-2') }}"
      DBUsername: "{{ lookup('aws_ssm', '/config/CKAN/STAGING/db/master_user', region='ap-southeast-2') }}"
      DBPrivileges: "ALL"
      Environment: STAGING
      Platform: CKAN
      PubliclyAccessible: "false"
      MultiAZ: "true"
      Subnets: STAGINGCKANDBSubnet
      VPC: CKANVpc-STAGING
      StackTLD: ckan.staging-services.qld.gov.au
    tags:
      Environment: STAGING
      Service: CKAN
      itoc_monitored: 'false'
      Division: "Qld Online"
      Owner: "Development and Delivery"
      Version: "1.0"
      PowerManaged: "No"

  - name: CKAN-TRAINING-RDS
    state: "{{ state | default('present')}}"
    region: ap-southeast-2
    disable_rollback: true
    template: "templates/database.cfn.yml"
    template_parameters:
      DBAllocatedStorage: "100"
      DBClass: db.t3.medium
      DBEngine: postgres
      DBEngineVersion: 10.6
      DBName: ckan
      StorageEncrypted: "False"
      DBPassword: "{{ lookup('aws_ssm', '/config/CKAN/TRAINING/db/master_password', region='ap-southeast-2') }}"
      DBUsername: "{{ lookup('aws_ssm', '/config/CKAN/TRAINING/db/master_user', region='ap-southeast-2') }}"
      DBPrivileges: "ALL"
      Environment: TRAINING
      Platform: CKAN
      PubliclyAccessible: "false"
      MultiAZ: "false"
      Subnets: TRAININGCKANDBSubnet
      VPC: CKANVpc-TRAINING
      StackTLD: training.ckan.devpit140cs.qgov.net.au
    tags:
      Environment: TRAINING
      Service: CKAN
      itoc_monitored: "false"
      Division: "Qld Online"
      Owner: "Development and Delivery"
      Version: "1.0"
      PowerManaged: "Yes"

  - name: CKAN-DEV-RDS
    state: "{{ state | default('present')}}"
    region: ap-southeast-2
    disable_rollback: true
    template: "templates/database.cfn.yml"
    template_parameters:
      DBAllocatedStorage: "100"
      DBClass: db.t3.medium
      DBEngine: postgres
      DBEngineVersion: 10.6
      DBName: ckan
      StorageEncrypted: "False"
      DBPassword: "{{ lookup('aws_ssm', '/config/CKAN/DEV/db/master_password', region='ap-southeast-2') }}"
      DBUsername: "{{ lookup('aws_ssm', '/config/CKAN/DEV/db/master_user', region='ap-southeast-2') }}"
      DBPrivileges: "ALL"
      Environment: DEV
      Platform: CKAN
      PubliclyAccessible: "false"
      MultiAZ: "false"
      Subnets: DEVCKANDBSubnet
      VPC: CKANVpc-DEV
      StackTLD: internal.ckan.devpit140cs.qgov.net.au
    tags:
      Environment: DEV
      Service: CKAN
      itoc_monitored: "false"
      Division: "Qld Online"
      Owner: "Development and Delivery"
      Version: "1.0"
      PowerManaged: "Yes"
