---
cloudformation_stacks:
  - name: CKAN-PROD-RDS
    state: present
    region: ap-southeast-2
    disable_rollback: true
    template: "templates/database.yml"
    template_parameters:
      DBAllocatedStorage: "100"
      DBClass: db.m4.large
      DBEngine: postgres
      DBEngineVersion: 10.6
      DBName: ckan
      StorageEncrypted: "True"
      DBPassword: "{{ lookup('aws_ssm', 'CKAN_PROD_MASTER_DBPASS', region='ap-southeast-2') }}"
      DBUsername: "{{ lookup('aws_ssm', 'CKAN_PROD_MASTER_DBUSER', region='ap-southeast-2') }}"
      DBPrivileges: "ALL"
      Environment: PROD
      Platform: CKAN
      PubliclyAccessible: "true"
      MultiAZ: "true"
      Subnets: PRODCKANDBSubnet
      VPC: CKANVpc-PROD
    tags:
      Environment: PROD
      Service: "CKAN"
      itoc_monitored: "true"
      Division: "Qld Online"
      Owner: "Development and Delivery"
      Version: "1.0"

  - name: CKAN-STAGING-RDS
    state: present
    region: ap-southeast-2
    disable_rollback: true
    template: "templates/database.yml"
    template_parameters:
      DBAllocatedStorage: '50'
      DBClass: db.t2.large
      DBEngine: postgres
      DBEngineVersion: 10.6
      DBName: ckan
      StorageEncrypted: "True"
      DBPassword: "{{ lookup('aws_ssm', 'CKAN_STAGING_MASTER_DBPASS', region='ap-southeast-2') }}"
      DBUsername: "{{ lookup('aws_ssm', 'CKAN_STAGING_MASTER_DBUSER', region='ap-southeast-2') }}"
      DBPrivileges: "ALL"
      Environment: STAGING
      Platform: CKAN
      PubliclyAccessible: "true"
      MultiAZ: "false"
      Subnets: STAGINGCKANDBSubnet
      VPC: CKANVpc-STAGING
    tags:
      Environment: STAGING
      Service: "CKAN"
      itoc_monitored: 'false'
      Division: "Qld Online"
      Owner: "Development and Delivery"
      Version: "1.0"

  - name: CKAN-DEV-RDS
    state: present
    region: ap-southeast-2
    disable_rollback: true
    template: "templates/database.yml"
    template_parameters:
      DBAllocatedStorage: "100"
      DBClass: db.t2.medium
      DBEngine: postgres
      DBEngineVersion: 10.6
      DBName: ckan
      StorageEncrypted: "False"
      DBPassword: "{{ lookup('aws_ssm', 'CKAN_DEV_MASTER_DBPASS', region='ap-southeast-2') }}"
      DBUsername: "{{ lookup('aws_ssm', 'CKAN_DEV_MASTER_DBUSER', region='ap-southeast-2') }}"
      DBPrivileges: "ALL"
      Environment: DEV
      Platform: CKAN
      PubliclyAccessible: "true"
      MultiAZ: "false"
      Subnets: DEVCKANDBSubnet
      VPC: CKANVpc-DEV
    tags:
      Environment: DEV
      Service: "CKAN"
      itoc_monitored: "true"
      Division: "Qld Online"
      Owner: "Development and Delivery"
      Version: "1.0"
      PowerManaged: "Yes"
