---
#
# Run an OpsWorks deployment on a layer. This could be a standard lifecycle event (setup, deploy, configure) or a custom recipe.
#

- name: Identify OpsWorks stack
  shell: >
    aws opsworks describe-stacks --region us-east-1 --query "Stacks[].{StackId:StackId, Name: Name}[?Name=='{{ Stack_Name }}'] | [0].StackId" --output text
  register: opsworks_stack
  when: stack_id is not defined and Stack_Name is defined
- set_fact:
    stack_id: "{{ opsworks_stack.stdout_lines[0] }}"
  when: stack_id is not defined and Stack_Name is defined

# this can get underway before we finish our reconnaissance
- name: Refresh cookbook
  shell: >
    aws opsworks create-deployment --region us-east-1 --stack-id {{ stack_id }} --command Name=update_custom_cookbooks --output text
  register: opsworks_deployment
- set_fact:
    cookbook_deployment_id: "{{ opsworks_deployment.stdout_lines[0] }}"

- name: Identify OpsWorks layer
  shell: >
    aws opsworks describe-layers --region us-east-1 --stack-id {{ stack_id }} --query "Layers[].{LayerId: LayerId, Shortname: Shortname}[?Shortname=='{{ Layer_Name }}']|[0].LayerId" --output text
  register: opsworks_layer
- set_fact:
    layer_id: "{{ opsworks_layer.stdout_lines[0] }}"

- name: Identify OpsWorks app
  shell: >
    aws opsworks describe-apps --region us-east-1 --stack-id {{ stack_id }} --query "Apps[].{AppId: AppId, Shortname: Shortname}[?Shortname=='{{ App_Name }}']|[0].AppId" --output text
  register: opsworks_app
- set_fact:
    app_id: "{{ opsworks_app.stdout_lines[0] }}"

- name: Wait for cookbook update to finish
  shell: >
    aws opsworks describe-deployments --region us-east-1 --deployment-id {{ cookbook_deployment_id }} --query "Deployments|[0].Status" --output text
  register: result
  until: result.stdout_lines[0] != 'running'
  retries: 6
  delay: 20
- fail:
    msg: "Failed to update cookbook - aborting"
  when: result.stdout_lines[0] != 'successful'

- name: Run deployment on layer
  shell: >
    aws opsworks create-deployment --region us-east-1 --stack-id {{ stack_id }} --layer-id {{ layer_id }} --app-id {{ app_id }} --command Name={{ Deployment_Type | default('deploy') }} --output text
  register: opsworks_deployment
- set_fact:
    deployment_id: "{{ opsworks_deployment.stdout_lines[0] }}"

- name: Wait for deployment to finish
  shell: >
    aws opsworks describe-deployments --region us-east-1 --deployment-id {{ deployment_id }} --query "Deployments|[0].Status" --output text
  register: result
  until: result.stdout_lines[0] != 'running'
  retries: 6
  delay: 20
- fail:
    msg: "Failed to deploy - aborting"
  when: result.stdout_lines[0] != 'successful'
