Description: Cloudfront Distribution for fronting an application.
Parameters:
  ACMCertificateARN:
    Description: ARN for certificate to be used by CloudFront
    Type: String
  Domain:
    Description: Domain pointing to EC2 load balancer
    Type: String
  WebOrigin:
    Description: Platform ELB
    Type: String
  Environment:
    Description: Platform environment
    Type: String
  Platform:
    Description: Name of the platform ie GI, Services, Static,etc
    Type: String
  LogBucketName:
    Description: Name of the S3 logging bucket.
    Type: String
  WebACLId:
    Description: WAF web ACL Id .
    Type: String

Resources:
  DistributionConfig:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - Ref: Domain
          - !Sub "www.${Domain}"
        DefaultCacheBehavior:
          AllowedMethods:
          - GET
          - HEAD
          - POST
          - DELETE
          - OPTIONS
          - PUT
          - PATCH
          Compress: true
          ForwardedValues:
            Cookies:
              Forward: all
            QueryString: 'true'
            Headers:
             - "*"
          TargetOriginId: 'WebOrigin'
          ViewerProtocolPolicy: redirect-to-https
        DefaultRootObject: /
        Enabled: true
        Logging:
          Bucket: !Sub "${LogBucketName}.s3.amazonaws.com"
          IncludeCookies: true
          Prefix: !Sub "cloudfront-logs/${Platform}/${Environment}/"
        Origins:
        - DomainName:
            Fn::ImportValue: !Ref WebOrigin
          Id: 'WebOrigin'
          CustomOriginConfig:
            OriginProtocolPolicy: "match-viewer"      # required, accepts http-only, match-viewer, https-only
        PriceClass: PriceClass_All
        WebACLId:
          Fn::ImportValue: !Ref WebACLId
        HttpVersion: 'http2'
        #IsIPV6Enabled: 'true'
        ViewerCertificate:
          AcmCertificateArn:
            Ref: ACMCertificateARN
          SslSupportMethod: sni-only
        Comment: !Sub "${Environment}-${Platform} ${Domain}"

Outputs:
  CloudfrontAliasDNSName:
    Value:
      Fn::GetAtt:
      - DistributionConfig
      - DomainName
    Export:
      Name:
        Fn::Join:
          - ""
          - - !Ref Environment
            - !Ref Platform
            - "CloudfrontAliasDNSName"

  CloudfrontAliasHostedZoneID:
    Value: "Z2FDTNDATAQYW2" # All CloudFront distributions are in this zone, see https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-aliastarget.html
    Export:
      Name:
        Fn::Join:
          - ""
          - - !Ref Environment
            - !Ref Platform
            - "CloudfrontAliasHostedZoneID"

  AwsAccount:
    Value: !Ref "AWS::AccountId"
