Description: S3 bucket and associated origin access identity for CloudFront logging
Parameters:
  LogBucketName:
    Description: Name of the S3 logging bucket.
    Type: String

Resources:
  OriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: Identity for CloudFront to access S3.

  LoggingBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Ref LogBucketName
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  LoggingBucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: !Ref LoggingBucket
      PolicyDocument:
        Statement:
          - Action:
              - "s3:PutObject"
            Effect: "Allow"
            Resource:
              !Sub "arn:aws:s3:::${LoggingBucket}/*"
            Principal:
              CanonicalUser:
                Fn::GetAtt:
                  - OriginAccessIdentity
                  - S3CanonicalUserId

Outputs:
  CloudFrontOAI:
    Value: !Ref OriginAccessIdentity
    Description: CloudFront Origin Access Identity for accessing S3
    Export:
      Name: CKANCloudFrontOAI
