---
AWSTemplateFormatVersion: '2010-09-09'
Description: |-
  Creates OpsWorks Applications for CKAN Stack extensions.
  Current extension list:
  Legacy theme
  Queensland Government extension

Parameters:
  Environment:
    Description: Select a stack version.
    Type: String
    Default: STAGING
    AllowedValues:
      - DEV
      - TRAINING
      - STAGING
      - PROD
  OpsWorksStack:
    Description: The exported name of the OpsWorks Stack ID
    Type: String
  ApplicationName:
    Description: Name of the application (ie. GI or Services, etc)
    Type: String
  ApplicationId:
    Description: All-lowercase identifier for the application (eg 'gi', 'services', etc)
    Type: String
    ConstraintDescription: Must contain only lowercase/numeric/hyphen/underscore.
    AllowedPattern: '[-_a-z0-9]*'
  CKANThemeSource:
    Description: URL for zip archive.
    Type: String
  CKANThemeSourceType:
    Description: Theme source type eg s3.
    Type: String
    Default: s3
  QgovExtensionSource:
    Description: URL for QGOV CKAN extension.
    Default: https://github.com/qld-gov-au/ckan-ex-qgov.git
    Type: String
  QgovExtensionRevision:
    Description: Branch/tag name in repository to checkout.
    Default: master
    Type: String

Conditions:
  DeployLegacyTheme:
    Fn::Not:
      - Fn::Equals:
        - "none"
        - !Ref CKANThemeSource

Resources:
  OpwxAppCKANTheme:
    Condition: DeployLegacyTheme
    Type: AWS::OpsWorks::App
    Properties:
      AppSource:
        Type: !Ref CKANThemeSourceType
        Url: !Ref CKANThemeSource
      Description: !Sub "Page templates and public assets for ${ApplicationName}-${Environment}"
      EnableSsl: false
      Name: !Sub "${ApplicationName} ${Environment} theme"
      Shortname: !Sub "${ApplicationId}-theme-${Environment}"
      StackId:
        Fn::ImportValue: !Ref OpsWorksStack
      Type: other

  CKANExtQGOV:
    Type: AWS::OpsWorks::App
    Properties:
      AppSource:
        Type: git
        Url: !Ref QgovExtensionSource
        Revision: !Ref QgovExtensionRevision
      Description: CKAN Extension for Queensland Government
      EnableSsl: false
      Name: !Sub "ckanext-qgov-${Environment}"
      Shortname: ckanext-qgov
      StackId:
        Fn::ImportValue: !Ref OpsWorksStack
      Type: other
