---
AWSTemplateFormatVersion: '2010-09-09'
Description: |-
  Creates OpsWorks Applications for CKAN Stack extensions.
  Current extension list:
  Queensland Government extension

Parameters:
  Environment:
    Description: Select a stack version.
    Type: String
    Default: STAGING
    AllowedValues:
      - DEV
      - TRAINING
      - STAGING
      - PROD
  OpsWorksStack:
    Description: The exported name of the OpsWorks Stack ID
    Type: String
  QgovExtensionSource:
    Description: URL for QGOV CKAN extension.
    Default: https://github.com/qld-gov-au/ckan-ex-qgov.git
    Type: String

Resources:
  CKANExtQGOV:
    Type: AWS::OpsWorks::App
    Properties:
      AppSource:
        Type: git
        Url: !Ref QgovExtensionSource
      Description: CKAN Extension for Queensland Government
      EnableSsl: false
      Name: !Sub "ckanext-qgov-${Environment}"
      Shortname: ckanext-qgov
      StackId:
        Fn::ImportValue: !Ref OpsWorksStack
      Type: other
