---
AWSTemplateFormatVersion: '2010-09-09'
Description: |-
  Creates OpsWorks Applications for CKAN Stack extensions.
  Current extension list:
  Queensland Government extension
  Trak
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Stack Parameters
      Parameters:
      - OpsWorksStack
    ParameterLabels:
      OpsWorksStack:
        default: What OpsWorks Stack do you want to add CKAN Extensions to?

Parameters:
  Environment:
    Description: Select a stack version.
    Type: String
    Default: STAGING
    AllowedValues:
      - DEV
      - TRAINING
      - STAGING
      - PROD
  OpsWorksStack:
    Description: The exported name of the OpsWorks Stack ID
    Type: String
  QgovExtensionSource:
    Description: URL for QGOV CKAN extension.
    Default: https://github.com/qld-gov-au/ckan-ex-qgov.git
    Type: String
  QgovExtensionRevision:
    Description: QGOV extension repository branch to check out.
    Default: QOL-4495-fix-bugs-for-AWS
    Type: String
  TrakExtensionSource:
    Description: URL for Trak extension.
    Default: https://github.com/XVTSolutions/ckanext-trak.git
    Type: String
  TrakExtensionRevision:
    Description: Trak extension repository branch to check out.
    Default: master
    Type: String

Resources:
  CKANExtQGOV:
    Type: AWS::OpsWorks::App
    Properties:
      AppSource:
        Type: git
        Revision: !Ref QgovExtensionRevision
        Url: !Ref QgovExtensionSource
      Description: CKAN Extension for Queensland Government
      EnableSsl: false
      Name: !Sub "ckanext-qgov-${Environment}"
      Shortname: ckanext-qgov
      StackId:
        Fn::ImportValue: !Ref OpsWorksStack
      Type: other

  CKANExtTrak:
    Type: AWS::OpsWorks::App
    Properties:
      AppSource:
        Type: git
        Revision: !Ref TrakExtensionRevision
        Url: !Ref TrakExtensionSource
      Description: CKAN Trak Extension
      EnableSsl: false
      Name: !Sub "ckanext-trak-${Environment}"
      Shortname: ckanext-trak
      StackId:
        Fn::ImportValue: !Ref OpsWorksStack
      Type: other

  # this is temporary
  CKANExtShowcase:
    Type: AWS::OpsWorks::App
    Properties:
      AppSource:
        Type: git
        Revision: master
        Url: https://github.com/ckan/ckanext-showcase.git
      Description: CKAN Showcase Extension
      EnableSsl: false
      Name: !Sub "ckanext-showcase-${Environment}"
      Shortname: ckanext-showcase
      StackId:
        Fn::ImportValue: !Ref OpsWorksStack
      Type: other

Outputs:
  QGov:
    Value:
      Ref: CKANExtQGOV
    Description: CKAN Queensland Government extension App ID
  Trak:
    Value:
      Ref: CKANExtTrak
    Description: CKAN Trak extension App ID
