AWSTemplateFormatVersion: 2010-09-09
Description: Creates an EFS filesystem stack to support CKAN.

Outputs:
  FileSystem:
    Value: !Ref SharedFileSystem
    Description: Filesystem ID
    Export:
      Name: !Sub "${Environment}${ApplicationName}-FileSystem"

Parameters:
  ApplicationName:
    Description: Name of the application (ie. GI or Services, etc)
    Type: String
  Environment:
    Description: Stack environment eg DEV, TRAINING
    Type: String
    Default: STAGING
    AllowedValues:
      - DEV
      - TRAINING
      - STAGING
      - PROD
  StackTLD:
    Description: Exported name of the private top-level domain name for the stack
    Type: String
  StackZone:
    Description: Exported name of the Route53 hosted zone ID.
    Type: String
  StackVPC:
    Description: The exported name for the existing VPC ID.
    Type: String
  DbSubnets:
    Type: String
    Description: The base name for the exported data layer subnet IDs, eg if the exports are 'PRODMyApplicationDbSubnetA' and 'PRODMyApplicationDbSubnetB', then this would be 'PRODMyApplicationDbSubnet'
  AdminSG:
    Description: The exported name of the security group ID containing sysadmin inbound rules
    Type: String

Resources:
  SharedFileSystem:
    Type: AWS::EFS::FileSystem
    Properties:
      PerformanceMode: generalPurpose
      FileSystemTags:
        -
          Key: Name
          Value:
            Fn::Join:
              - "-"
              - - !Ref Environment
                - !Ref AWS::StackName
                - "efs"

  MountTargetSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId:
        Fn::ImportValue: !Ref StackVPC
      GroupDescription: Security group for mount target
      SecurityGroupIngress:
        IpProtocol: tcp
        FromPort: 2049
        ToPort: 2049
        SourceSecurityGroupId:
          Fn::ImportValue: !Ref AdminSG

  MountTargetA:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref SharedFileSystem
      SubnetId:
        Fn::ImportValue: !Sub "${DbSubnets}A"
      SecurityGroups:
        - !Ref MountTargetSecurityGroup

  MountTargetB:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref SharedFileSystem
      SubnetId:
        Fn::ImportValue: !Sub "${DbSubnets}B"
      SecurityGroups:
        - !Ref MountTargetSecurityGroup

  MountTargetC:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref SharedFileSystem
      SubnetId:
        Fn::ImportValue: !Sub "${DbSubnets}C"
      SecurityGroups:
        - !Ref MountTargetSecurityGroup

  EFSCNAME:
    Type: AWS::Route53::RecordSet
    Properties:
      Type: CNAME
      TTL: 60
      Name:
        Fn::Join:
          - ""
          - - !Ref Environment
            - "efs."
            - Fn::ImportValue: !Ref StackTLD
      HostedZoneId:
        Fn::ImportValue: !Ref StackZone
      ResourceRecords:
        - Fn::Join:
          - "."
          - - !Ref SharedFileSystem
            - "efs"
            - !Ref AWS::Region
            - amazonaws.com
