AWSTemplateFormatVersion: '2010-09-09'
Description: |
  CloudFormation template to create IAM role for GitHub Actions OIDC with permissions to deploy to an environment.
  See https://aws.amazon.com/blogs/security/use-iam-roles-to-connect-github-actions-to-actions-in-aws/
  And https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services

Parameters:
  Environment:
    Type: String
    Default: 'DEV'
    Description: Which environment this role is for (DEV|TEST|STAGING|PROD)
  GitHubOrg:
    Type: String
    Description: GitHub organization or user name.
    Default: 'qld-gov-au'
  RepoName:
    Type: String
    Description: GitHub repository name.
    Default: 'ckan-qld-infrastructure'
  GitHubOIDCProviderARN:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: '/config/GitHubOIDCProviderARN'
    Description: ARN of the GitHubOIDCProvider


Resources:
#NOTE: This usually is created once per aws acccount, leave this in as reference
#  GitHubOIDCProvider:
#    Type: "AWS::IAM::OIDCProvider"
#    Properties:
#      Url: "https://token.actions.githubusercontent.com"
#      ClientIdList:
#        - "sts.amazonaws.com"
#      ThumbprintList:
#        - "6938fd4d98bab03faadb97b34396831e3780aea1"  # This thumbprint is for GitHub's SSL certificate

  GitHubActionsRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Federated:
                - !Ref GitHubOIDCProviderARN
            Action:
              - "sts:AssumeRoleWithWebIdentity"
            Condition:
              StringEquals:
                "token.actions.githubusercontent.com:aud": "sts.amazonaws.com"
                "token.actions.githubusercontent.com:sub": #username
                  - !Sub "repo:${GitHubOrg}/${RepoName}:environment:${Environment}" #username when from environment deployment
      Policies:
        - PolicyName: "DeployPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              # TODO Reduce to minimum necessary privileges
              - Effect: "Allow"
                Action:
                  - "*"
                Resource:
                  - "*"

Outputs:
  RoleArn:
    Description: "The ARN of the IAM role for GitHub Actions."
    Value: !GetAtt GitHubActionsRole.Arn
