---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Creates instances for OpsWorks CKAN Stack service layer.'
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: OpsWorks Stack Details
        Parameters:
          - Environment
          - OpsWorksStack
          - DataPusherLayer
          - SolrLayer
      - Label:
          default: Stack Instance Details
        Parameters:
          - ServicesEC2Size

    ParameterLabels:
      Environment:
        default: What version is this OpsWorks stack (eg STAGING)?
      ServicesEC2Size:
        default: What instance size do you want to use for Service Instances?
      OpsWorksStack:
        default: What OpsWorks stack do you want to provision instances into?
      DataPusherLayer:
        default: What is the DataPusher Layer ID of the stack?
      SolrLayer:
        default: What is the Solr Layer ID of the stack?

Parameters:
  Environment:
    Description: Select a stack version.
    Type: String
    Default: STAGING
    AllowedValues:
      - DEV
      - TRAINING
      - STAGING
      - PROD
  ServicesEC2Size:
    Description: Select EC2 Instance Size.
    Type: String
    Default: t3.small
    AllowedValues:
      - t3.small
      - t3.medium
      - t3.large
      - m3.medium
      - m5.large
      - m5.xlarge
      - m5.2xlarge
      - m5.4xlarge
      - m4.10xlarge
      - m5.12xlarge
  OpsWorksStack:
    Description: The exported name of the OpsWorks Stack ID.
    Type: String
  DataPusherLayer:
    Description: The exported name of the OpsWorks DataPusher Stack Layer ID.
    Type: String
  SolrLayer:
    Description: The exported name of the OpsWorks Solr Stack Layer ID.
    Type: String

Resources:
  OpswxEC2Services1:
    Type: AWS::OpsWorks::Instance
    Properties:
      RootDeviceType: ebs
      InstallUpdatesOnBoot: true
      InstanceType: !Ref ServicesEC2Size
      LayerIds:
        - Fn::ImportValue: !Ref DataPusherLayer
        - Fn::ImportValue: !Ref SolrLayer
      StackId:
        Fn::ImportValue: !Ref OpsWorksStack

Outputs:
  ServiceInstance:
    Value: !Ref OpswxEC2Services1
    Description: Services Node Instance Id
