---
AWSTemplateFormatVersion: '2010-09-09'
Description: |-
  Creates OpsWorks Applications for CKAN Stack extensions developed by Salsa Digital.
  Current extension list:
  DataQld
  DataQldTheme
  ODICertificates
  DCAT
  Scheming
  DataRequests
  Validation
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Stack Parameters
      Parameters:
      - OpsWorksStack
    ParameterLabels:
      OpsWorksStack:
        default: What OpsWorks Stack do you want to add CKAN Extensions to?

Parameters:
  Environment:
    Description: Select a stack version.
    Type: String
    Default: STAGING
    AllowedValues:
      - DEV
      - TRAINING
      - STAGING
      - PROD
  OpsWorksStack:
    Description: The exported name of the OpsWorks Stack ID
    Type: String
  DataQldExtensionSource:
    Description: URL for Queensland Government Open Data extension.
    Default: https://github.com/qld-gov-au/ckanext-data-qld.git
    Type: String
  DataQldExtensionRevision:
    Description: Branch/tag name in repository to checkout.
    Default: master
    Type: String
  DataQldThemeExtensionSource:
    Description: URL for Queensland Government Open Data theme extension.
    Default: https://github.com/qld-gov-au/ckanext-data-qld-theme.git
    Type: String
  DataQldThemeExtensionRevision:
    Description: Branch/tag name in repository to checkout.
    Default: master
    Type: String
  ODIExtensionSource:
    Description: URL for ODI Certificates extension
    Default: https://github.com/qld-gov-au/ckanext-odi-certificates.git
    Type: String
  ODIExtensionRevision:
    Description: Branch/tag name in repository to checkout.
    Default: master
    Type: String
  DCATExtensionSource:
    Description: URL for DCAT extension
    Default: https://github.com/ckan/ckanext-dcat.git
    Type: String
  DCATExtensionRevision:
    Description: Branch/tag name in repository to checkout.
    Default: master
    Type: String
  SchemingExtensionSource:
    Description: URL for Scheming extension
    Default: https://github.com/ckan/ckanext-scheming.git
    Type: String
  SchemingExtensionRevision:
    Description: Branch/tag name in repository to checkout.
    Default: master
    Type: String
  DataRequestsExtensionSource:
    Description: URL for Data Requests extension
    Default: https://github.com/qld-gov-au/ckanext-datarequests.git
    Type: String
  DataRequestsExtensionRevision:
    Description: Branch/tag name in repository to checkout.
    Default: master
    Type: String
  ValidationExtensionSource:
    Description: URL for Validation extension
    Default: https://github.com/frictionlessdata/ckanext-validation
    Type: String
  ValidationExtensionRevision:
    Description: Branch/tag name in repository to checkout.
    Default: master
    Type: String

Resources:
  CKANExtDataQld:
    Type: AWS::OpsWorks::App
    Properties:
      AppSource:
        Type: git
        Url: !Ref DataQldExtensionSource
        Revision: !Ref DataQldExtensionRevision
      Description: CKAN Extension for Queensland Government Open Data
      EnableSsl: false
      Name: !Sub "ckanext-data-qld-${Environment}"
      Shortname: ckanext-data-qld
      StackId:
        Fn::ImportValue: !Ref OpsWorksStack
      Type: other

  CKANExtDataQldTheme:
    Type: AWS::OpsWorks::App
    Properties:
      AppSource:
        Type: git
        Url: !Ref DataQldThemeExtensionSource
        Revision: !Ref DataQldThemeExtensionRevision
      Description: CKAN Extension for Queensland Government Open Data theme
      EnableSsl: false
      Name: !Sub "ckanext-data-qld-theme-${Environment}"
      Shortname: ckanext-data-qld-theme
      StackId:
        Fn::ImportValue: !Ref OpsWorksStack
      Type: other

  CKANExtODICertificates:
    Type: AWS::OpsWorks::App
    Properties:
      AppSource:
        Type: git
        Url: !Ref ODIExtensionSource
        Revision: !Ref ODIExtensionRevision
      Description: CKAN Extension for ODI Certificates
      EnableSsl: false
      Name: !Sub "ckanext-odi-certificates-${Environment}"
      Shortname: ckanext-odi-certificates
      StackId:
        Fn::ImportValue: !Ref OpsWorksStack
      Type: other

  CKANExtDCAT:
    Type: AWS::OpsWorks::App
    Properties:
      AppSource:
        Type: git
        Url: !Ref DCATExtensionSource
        Revision: !Ref DCATExtensionRevision
      Description: CKAN Extension for DCAT
      EnableSsl: false
      Name: !Sub "ckanext-dcat-${Environment}"
      Shortname: ckanext-dcat
      StackId:
        Fn::ImportValue: !Ref OpsWorksStack
      Type: other

  CKANExtScheming:
    Type: AWS::OpsWorks::App
    Properties:
      AppSource:
        Type: git
        Url: !Ref SchemingExtensionSource
        Revision: !Ref SchemingExtensionRevision
      Description: CKAN Extension for Scheming
      EnableSsl: false
      Name: !Sub "ckanext-scheming-${Environment}"
      Shortname: ckanext-scheming
      StackId:
        Fn::ImportValue: !Ref OpsWorksStack
      Type: other

  CKANExtDataRequests:
    Type: AWS::OpsWorks::App
    Properties:
      AppSource:
        Type: git
        Url: !Ref DataRequestsExtensionSource
        Revision: !Ref DataRequestsExtensionRevision
      Description: CKAN Extension for Data Requests
      EnableSsl: false
      Name: !Sub "ckanext-datarequests-${Environment}"
      Shortname: ckanext-datarequests
      StackId:
        Fn::ImportValue: !Ref OpsWorksStack
      Type: other

  CKANExtValidation:
    Type: AWS::OpsWorks::App
    Properties:
      AppSource:
        Type: git
        Url: !Ref ValidationExtensionSource
        Revision: !Ref ValidationExtensionRevision
      Description: CKAN Extension for Data Requests
      EnableSsl: false
      Name: !Sub "ckanext-validation-${Environment}"
      Shortname: ckanext-validation
      StackId:
        Fn::ImportValue: !Ref OpsWorksStack
      Type: other
