AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  Environment:
    Description: Platform environment
    Type: String
  Platform:
    Description: Name of the platform ie GI, Services, Static
    Type: String
    Default: CKAN
Resources:
  WebACLv2:
    Type: "AWS::WAFv2::WebACL"
    Properties:
      Name: !Sub "${Environment}-${Platform}-WebACLv2"
      Description: !Sub "${Environment} ${Platform} WAFv2 Web ACL to block traffic based on defined rules."
      Scope: CLOUDFRONT
      DefaultAction:
        Allow: {}
      VisibilityConfig:
        CloudWatchMetricsEnabled: true
        MetricName: "WafWebACL"
        SampledRequestsEnabled: true
      Rules:
        - Name: !Sub "${Environment}-${Platform}-RateLimitRule"
          Priority: 1
          Action:
            Block: {}
          Statement:
            RateBasedStatement:
              AggregateKeyType: "IP"
              EvaluationWindowSec: 300
              Limit: 5000
          VisibilityConfig:
            CloudWatchMetricsEnabled: true
            MetricName: "RateLimitRule"
        - Name: !Sub "${Environment}-${Platform}-APIRateLimitRule"
          # Throttle API requests more aggressively than general requests
          Priority: 2
          Action:
            Block: {}
          Statement:
            RateBasedStatement:
              AggregateKeyType: "IP"
              EvaluationWindowSec: 60
              Limit: 60
              ScopeDownStatement:
                RegexMatchStatement:
                  FieldToMatch:
                    UriPath: {}
                  RegexString:
                    /api/
                  TextTransformations:
                    - Priority: 0
                      Type: NONE
          VisibilityConfig:
            CloudWatchMetricsEnabled: true
            MetricName: "APIRateLimitRule"
        - Name: !Sub "${Environment}-${Platform}-XSSRule"
          Priority: 3
          Action:
            Block: {}
          Statement:
            XssMatchStatement:
              FieldToMatch:
                UriPath: {}
              TextTransformations:
                - Priority: 0
                  Type: NONE
          VisibilityConfig:
            CloudWatchMetricsEnabled: true
            MetricName: "XSSRule"
            SampledRequestsEnabled: true

  WebACL:
    Type: "AWS::WAF::WebACL"
    Properties:
      Name: !Sub "${Environment} ${Platform} Web ACL to block traffic based on defined rules. "
      DefaultAction:
        Type: "ALLOW"
      MetricName: "WafWebACL"
      Rules:
        - Priority: 1
          Action:
            Type: "BLOCK"
          RuleId:
            Ref: "XSSRule"

  DetectXSS:
    Type: "AWS::WAF::XssMatchSet"
    Properties:
      Name: !Sub "${Environment} ${Platform} XssMatchSet"
      XssMatchTuples:
        -
          FieldToMatch:
            Type: "URI"
          TextTransformation: "NONE"
        -
          FieldToMatch:
            Type: "QUERY_STRING"
          TextTransformation: "NONE"

  XSSRule:
    Type: "AWS::WAF::Rule"
    Properties:
      Name: !Sub "${Environment} ${Platform} XSSRule"
      MetricName: "XSSRule"
      Predicates:
        -
          DataId:
            Ref: "DetectXSS"
          Negated: false
          Type: "XssMatch"

  WAFWebACLIdParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/config/CKAN/${Environment}/common/waf_acl_id"
      Type: String
      Value: !GetAtt WebACLv2.Arn

Outputs:
  WebACLId:
    Value:
      Ref: WebACL
    Export:
      Name: !Sub "${Environment}${Platform}WebACLId"
