name: "Deploy to AWS"

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'DEV'
        type: choice
        options:
          - DEV
          - TEST
          - STAGING
          - PROD
      application:
        description: 'Application to deploy'
        required: true
        type: choice
        options:
          - OpenData
          - Publications
          - CKANTest
      dryRun:
        description: 'Dry Run deployment (set to false to deploy)'
        required: true
        type: boolean
        default: true

jobs:
  deploy:
    name: Deploy to ${{ github.event.inputs.application }} ${{ github.event.inputs.environment }} Environment
    runs-on: ubuntu-latest
    environment: OpenData-DEV
    env:
      bamboo_deploy_environment: ${{ github.event.inputs.environment }}
    concurrency:
      group: ${{ github.event.inputs.application }}-${{ github.event.inputs.environment }}-deployments
      cancel-in-progress: false

    permissions:
      id-token: write #Needed for AWS role switch
      contents: read

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          fetch-depth: 0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@e1253824e5c10ff9df46874f81ed3ec929e19cfd  # v6.3.0
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
          role-external-id: ${{ secrets.AWS_EXTERNAL_ID }}
          aws-region: ap-southeast-2

      - name: Save root directory
        run: echo "REPO_ROOT=$(pwd)" >> $GITHUB_ENV

      - name: "Deploy ${{ github.event.inputs.application }} to ${{ github.event.inputs.environment }}"
        run: |
          aws iam list-account-aliases | grep osssio-ckan
          greprc=$?
          if [ $greprc -eq 0 ]; then
            if [ "${{ github.event.inputs.dryRun }}" = "true" ]; then
              echo "'dryRun' flag is set, skipping deployment"
            else
              aws cloudformation create-stack --region ap-southeast-2 \
                --stack-name "${{ github.event.inputs.application }}-${{ github.event.inputs.environment }}-DEPLOYMENT" \
                --template-body file://templates/deployment-instance.cfn.yml \
                --parameters "ParameterKey=ApplicationName,ParameterValue=${{ github.event.inputs.application }}" \
                "ParameterKey=Environment,ParameterValue=${{ github.event.inputs.environment }}" \
                "ParameterKey=InfrastructureURL,ParameterValue=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY" \
                "ParameterKey=InfrastructureRevision,ParameterValue=${{ github.sha }}"
                "ParameterKey=LogBucket,ParameterValue=osssio-ckan-web-logs"
            fi
          else
            echo "we are not in ckan account, we did not run script";
            exit 1;
          fi
