---
#based on https://raw.githubusercontent.com/ckan/ckanext-scheming/master/.github/workflows/test.yml
# alternative https://github.com/ckan/ckan/blob/master/contrib/cookiecutter/ckan_extension/%7B%7Bcookiecutter.project%7D%7D/.github/workflows/test.yml
name: Tests
on:
  push:
  schedule:
    - cron: "0 0 1 * *"

jobs:
  test:
    strategy:
      matrix:
        application: [OpenData, Publications]
        target_environment: [DEV]
      fail-fast: false

    name: ${{ matrix.application }} ${{ matrix.target_environment }} infrastructure build
    runs-on: ubuntu-latest
    container: integratedexperts/ci-builder
    env:
      VARS_TYPE: ${{ matrix.application }}
      DEPLOY_ENV: ${{ matrix.target_environment }}

    steps:
      - uses: actions/checkout@v2
        timeout-minutes: 2

      - name: Build
        run: .circleci/build.sh
        timeout-minutes: 20

      - name: Test
        run: .circleci/test.sh
        timeout-minutes: 35

      - name: Retrieve screenshots
        if: failure()
        run: .circleci/process-artifacts.sh
        timeout-minutes: 1

      - name: Upload screenshots
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.application }} ${{ matrix.target_environment }} screenshots
          path: /tmp/artifacts/behave/screenshots
        timeout-minutes: 1
